import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const DEFAULT_SPEC = "https://app.checkcourt.de/api/v1/openapi";
const BANNER = "// Generated by scripts/generate.mjs from the CheckCourt OpenAPI spec. Do not edit.\n";

const source = process.env.CHECKCOURT_OPENAPI || DEFAULT_SPEC;
const outDir = new URL("../src/generated/", import.meta.url);

async function loadSpec(location) {
  if (/^https?:\/\//.test(location)) {
    const response = await fetch(location, { headers: { Accept: "application/json" } });
    if (!response.ok) throw new Error(`GET ${location} failed with HTTP ${response.status}`);
    return response.text();
  }
  return readFile(location, "utf8");
}

const spec = JSON.parse(await loadSpec(source));
// Hash the minified form so it matches the body served at /api/v1/openapi, whatever the source formatting.
const hash = createHash("sha256").update(JSON.stringify(spec)).digest("hex");

await writeFile(new URL("schema.d.ts", outDir), `${BANNER}\n${astToString(await openapiTS(spec))}`);
await writeFile(new URL("spec-hash.ts", outDir), `${BANNER}export const OPENAPI_SPEC_SHA256 = "${hash}";\n`);
console.log(`Generated types from ${source} (spec sha256 ${hash.slice(0, 12)})`);
